ALTER TABLE `integracao`
  ADD COLUMN `tipo_layout` ENUM('LAYOUT','CSV') NULL DEFAULT 'LAYOUT' AFTER `slug_group`,
  ADD COLUMN `layout_separador` VARCHAR(5) NULL DEFAULT ';' AFTER `tipo_layout`;


INSERT INTO `integracao_log_detalhe_erro` (`integracao_log_detalhe_erro_id`, `nome`, `tipo`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (18, 'Número do Celular inválido', 'E', 0, '2018-12-03 21:43:33', 0, NULL);


INSERT INTO `comunicacao_evento` (`comunicacao_tipo_id`, `nome`, `slug`, `descricao`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (2, 'OFERTA SEGURO (COTAÇÃO GERADA)', 'cotacao_gerada', 'OFERTA SEGURO (COTAÇÃO GERADA)', 0, '2019-04-15 19:53:02', 0, '2019-04-15 19:53:02');


INSERT INTO `comunicacao_template` (`comunicacao_tipo_id`, `comunicacao_engine_configuracao_id`, `descricao`, `slug`, `mensagem_titulo`, `mensagem_de`, `mensagem_anexo`, `mensagem`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (2, 3, 'OFERTA SEGURO (COTAÇÃO GERADA', 'cotacao_gerada', 'Oferta Seguro (Cotação Gerada', '-', NULL, 'Sr(a) {nome}, utiliza a seguinte URL para simular seu seguro. {url}', 0, '2019-04-15 19:56:21', 0, '2019-04-15 19:56:21');


INSERT INTO `integracao` (`integracao_id`, `parceiro_id`, `tipo`, `integracao_comunicacao_id`, `periodicidade_unidade`, `periodicidade`, `periodicidade_hora`, `proxima_execucao`, `ultima_execucao`, `nome`, `slug`, `descricao`, `script_sql`, `parametros`, `campo_chave`, `ambiente`, `host`, `porta`, `usuario`, `senha`, `diretorio`, `envia_vazio`, `habilitado`, `status`, `before_execute`, `after_execute`, `before_detail`, `after_detail`, `sequencia`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`, `slug_group`, `tipo_layout`, `layout_separador`) VALUES (97, 32, 'R', 1, 'D', 1, '01:00:00', '2019-04-16 01:00:00', '2019-04-15 22:19:19', 'RASTRECALL - OFERTA DE SEGUROS SMS', 'rastrecall-sms', 'RASTRECALL - OFERTA DE SEGUROS SMS', NULL, '0', 'cotacao_id', 'H', 'ftp.zazz.com.br', 21, 'zazz', 'vruReLsZFrWDWQhhCBsV', '/RASTRECALL/SMS/', 0, 1, 'A', '', '', 'app_integracao_rastrecall_sms', '', 0, 0, '2018-08-23 20:02:44', 0, '2019-04-15 22:19:19', 'ems-emissao', 'CSV', ';');


INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 68, 'F', 0, 'NOMENCLATURA DO ARQUIVO:', 'NOMENCLATURA DO ARQUIVO:', '', 'C', 34, 1, 0, 0, 1, 30, NULL, '', 'teste-arquivo.csv', 0, 0, 0, '2018-08-19 22:15:07', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 66, 'D', 0, 'NOME_FANTASIA\r\n', 'Nome Estipulante', '', 'C', 100, 0, 0, 0, 1, 99, '', '', '', 0, 0, 0, '2018-09-01 17:01:40', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 66, 'D', 1, 'NOTA_FISCAL\r\n', 'NUMERO DA NOTA FISCAL\r\n', '', NULL, 10, 0, 1, 1, 725, 734, 'nota_fiscal_numero', '', '0', 0, 0, 0, '2018-02-15 20:04:04', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 66, 'D', 2, 'SERIE\r\n', 'SERIE DA NOTA FISCAL\r\n', '', NULL, 1, 0, 0, 0, 725, 734, 'nota_fiscal_serie', '', '0', 0, 0, 0, '2018-02-15 20:04:04', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 66, 'D', 3, 'DATA_EMISSAO\r\n', 'Data de referência referente a emissão da apólice ou endosso AAAAMMDD', '', 'C', 8, 1, 0, 1, 119, 126, 'nota_fiscal_data', '', ' ', 8, 0, 0, '2018-08-23 21:31:07', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 66, 'D', 4, 'NOME_CLIENTE\r\n', 'Nome Cliente', '', 'C', 100, 0, 0, 1, 1, 99, 'nome', '', '', 0, 0, 0, '2018-09-01 17:01:40', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 66, 'D', 5, 'CPF_CNPJ\r\n', 'CPF="11111111111111","CNPJ=11111111111111"\r\n', '', NULL, 14, 0, 1, 1, 95, 108, 'cnpj_cpf', '', '0', 14, 0, 0, '2018-02-14 15:10:21', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 66, 'D', 6, 'RG_IE', 'RG ou IE', '', 'C', 20, 0, 0, 0, 440, 447, '', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 66, 'D', 7, 'DATA_NASC_CLIENTE\r\n', 'Data de nascimento do Beneficiario DD/mm/YYYY', 'd/m/Y', 'D', 10, 0, 0, 1, 440, 447, 'data_nascimento', '', ' ', 10, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 8, 'CEP\r\n', 'CEP do beneficiario', '', 'C', 10, 1, 0, 1, 410, 419, 'endereco_cep', '', ' ', 10, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 9, 'ENDERECO\r\n', 'Endereco', '', 'C', 100, 1, 0, 1, 410, 419, 'endereco_logradouro', '', ' ', 100, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 10, 'NUMERO\r\n', 'Endereco Numero', '', 'C', 20, 1, 0, 1, 410, 419, 'endereco_numero', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 11, 'COMPLEMENTO\r\n', 'Complemento', '', 'C', 20, 1, 0, 1, 410, 419, 'endereco_complemento', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 12, 'BAIRRO\r\n', 'Bairro', '', 'C', 100, 1, 0, 1, 410, 419, 'endereco_bairro', '', ' ', 100, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 13, 'CIDADE\r\n', 'Cidade', '', 'C', 100, 1, 0, 1, 410, 419, 'endereco_cidade', '', ' ', 100, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 14, 'UF', 'UF', '', 'C', 2, 1, 0, 1, 410, 419, 'endereco_estado', '', ' ', 2, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 15, 'FONE_CLIENTE\r\n', 'Telefone', '', 'C', 20, 0, 0, 0, 410, 419, '', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 16, 'CELULAR_CLIENTE\r\n', 'Celular', '', 'C', 20, 1, 0, 1, 410, 419, 'telefone', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 17, 'EMAIL_CLIENTE\r\n', 'Email', '', 'C', 100, 0, 0, 1, 410, 419, 'email', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 18, 'DESCRICAO\r\n', 'modelo', '', 'C', 100, 0, 0, 1, 410, 419, 'equipamento', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 19, 'CATEGORIA\r\n', 'Categoria', '', 'C', 100, 0, 0, 1, 410, 419, 'equipamento_categoria', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 20, 'MARCA\r\n', 'Marca', '', 'C', 100, 0, 0, 1, 410, 419, 'equipamento_marca', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 21, 'CODEBAR\r\n', 'CODEBAR', '', 'C', 100, 0, 0, 1, 410, 419, 'equipamento_codigo_barra', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 22, 'IMEI\r\n', 'IMEI', '', 'C', 100, 0, 0, 1, 410, 419, 'equipamento_imei', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
INSERT INTO `integracao_layout` (`integracao_id`, `integracao_detalhe_id`, `tipo`, `ordem`, `nome`, `descricao`, `formato`, `campo_tipo`, `tamanho`, `obrigatorio`, `campo_log`, `insert`, `inicio`, `fim`, `nome_banco`, `function`, `valor_padrao`, `qnt_valor_padrao`, `str_pad`, `deletado`, `criacao`, `alteracao_usuario_id`, `alteracao`) VALUES (97, 357, 'D', 23, 'PRECO_VENDA_LIQ\r\n', 'VALOR NF', '', 'C', 100, 0, 0, 1, 410, 419, 'nota_fiscal_valor', '', ' ', 20, 0, 0, '2018-10-18 14:23:12', 0, '0000-00-00 00:00:00');
